"""remove category enum field

Revision ID: 7e243e887d5d
Revises: 966bd6c43691
Create Date: 2026-06-09 12:19:50.235449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e243e887d5d'
down_revision: Union[str, Sequence[str], None] = '966bd6c43691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('type', postgresql.ENUM('INCOME', 'EXPENSE', name='categorytype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
